
name: laravel project deploy
on:
  push:
    branches:
      - master
jobs:
  steps:

    - name: Checkout

      uses: actions/checkout@v2

    - name: Deployment

      uses: Tofik100/test@master

      with:

        host: ${{ secrets.SSH_HOST }}

        key: ${{ secrets.SSH_PRIVATE_KEY }}

        username: ${{ secrets.SSH_USERNAME }}