
name: laravel project deploy
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: test
      uses: Tofik100/test@master
      with:
        
        SSH_HOST: ${{ secrets.SSH_HOST }}

        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}

        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}

        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

        SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}

        script: "cd /var/www/html/test && ./deployer.sh"