
name: laravel project deploy
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: test
      uses: Tofik100/test@master
      with:
        
        ssh_host: "51.68.94.64"
        ssh_user: "root"
        ssh_port: 22
        private_ssh_key: ${{ secrets.SSH_KEY }}
        ssh_known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}