
name: laravel project deploy
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
     - id: test
        - uses: ./.github/actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: test
      uses: Tofik100/test@master
      with:
        user: root
        host: 51.68.94.64
        password: ${{ secrets.SSH_PASSWORD }}
        script: 'cd /var/www/html/test && ./deployer.sh'