
deploy:

  runs-on: ubuntu-latest

  steps:

    - name: Checkout

      uses: actions/checkout@v2

    - name: Deployment

      uses: appleboy/ssh-action@main

      with:
        username: ${{ secrets.SSH_USERNAME }}

        key: ${{ secrets.SSH_PRIVATE_KEY }}

        host: ${{ secrets.SSH_HOST }}

        ssh_known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

        script: |

          cd /var/www/html/

          git checkout -f 

          git pull
