
name: laravel project deploy
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      id: gcloud
      uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: test
      uses: Tofik100/test@master
      with:
        ftp-server: ${{ secrets.FTP_SERVER }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}